# Generated by Django 4.2.6 on 2023-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_comm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialcommunication',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
