# Generated by Django 4.2.6 on 2024-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serial_comm", "0006_statesweekly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Averages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "WSPD",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "WDIR",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "ATMP",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "HUMD",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "RAIN",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "SRAD",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "BPRS",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "WDCH",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "DWPT",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "P12",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "P13",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "P14",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "P15",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "P16",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
            ],
        ),
    ]
