# Generated by Django 4.2.6 on 2023-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='elements',
            field=models.ManyToManyField(blank=True, null=True, to='controller.elements'),
        ),
    ]
