# Generated by Django 4.2.6 on 2023-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_programs_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.TextField()),
                ('programs', models.ManyToManyField(blank=True, null=True, to='controller.programs')),
            ],
        ),
    ]
