# Generated by Django 4.2.6 on 2023-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='styles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
