# Generated by Django 4.2.6 on 2023-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_panel_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='sequence',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
