# Generated by Django 4.2.6 on 2023-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_panel_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='sequence',
            field=models.JSONField(blank=True, max_length=256, null=True),
        ),
    ]
