# Generated by Django 4.2.6 on 2023-10-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_alter_panel_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
