# Generated by Django 4.2.6 on 2023-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_programs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='running_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
