# Generated by Django 4.2.6 on 2023-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_programs_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='panel_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
