# Generated by Django 4.2.6 on 2023-10-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_programs_panel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
