# Generated by Django 4.2.6 on 2023-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_panel_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='animation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
