# Generated by Django 4.2.6 on 2023-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, unique=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('running_time', models.PositiveIntegerField(default=1)),
                ('panel_code', models.TextField(blank=True, null=True)),
                ('animation', models.CharField(blank=True, max_length=255, null=True)),
                ('elements', models.ManyToManyField(blank=True, null=True, to='controller.elements')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.TextField(blank=True, null=True)),
                ('sequence', models.JSONField(blank=True, max_length=256, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programs', models.ManyToManyField(blank=True, null=True, to='controller.programs')),
            ],
        ),
    ]
