# Generated by Django 4.2.6 on 2023-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RTC', models.DateTimeField()),
                ('WSPD', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('WDIR', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('ATMP', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('HUMD', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('RAIN', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('SRAD', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('BPRS', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('WDCH', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('DWPT', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('P12', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('P13', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('P14', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('P15', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('P16', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
            ],
        ),
    ]
