# Generated by Django 4.2.6 on 2023-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_comm', '0002_serialcommunication_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcommunication',
            name='ATMP',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='BPRS',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='DWPT',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='HUMD',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='P12',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='P13',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='P14',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='P15',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='P16',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='RAIN',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='SRAD',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='WDCH',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='WDIR',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='serialcommunication',
            name='WSPD',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
    ]
