# Generated by Django 4.2.6 on 2023-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serial_comm", "0005_states_created_at_states_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatesWeekly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param", models.CharField(max_length=255)),
                ("count", models.IntegerField()),
                ("mean", models.FloatField()),
                ("min", models.FloatField()),
                ("max", models.FloatField()),
                ("std", models.FloatField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
